POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "second Blog",
    "author": "Ty Mak",
    "url": "123123.com",
    "likes": 32,
    "userId": "636268b75f4b5037b0939812"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "third Blog",
    "author": "Ty Mak",
    "url": "12312223.com",
    "likes": 2,
    "userId": "636268b75f4b5037b0939812"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InR5bWFrIiwiaWQiOiI2MzYyNjhiNzVmNGI1MDM3YjA5Mzk4MTIiLCJpYXQiOjE2NjczOTk0OTd9.NqI9gyU4hOPnD_30Szqbw4YrLu3u7MzBGX2KmiKo6zA

{
    "title": "trying token Blog",
    "author": "Ty Mak",
    "url": "12312223.com",
    "likes": 25
}